import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <br/><span className={styles.nextjs}>Next.js</span> <span className={styles.graphql}>GraphQL</span> Server
        </h1>

        <p className={styles.description}>
          Get started by visiting GraphiQL at{' '}
          <Link href="/api/graphql">
            <a>/api/graphql</a>
          </Link>
          <br />
          Edit the GraphQL handler at <code className={styles.code}>pages/api/graphql.ts</code>
        </p>

        
      </main>
    </div>
  )
}

export default Home
